version: '3.4'
services:
  graphql:
    build:
      context: graphql
      dockerfile: Dockerfile.dev
    volumes:
      - ./graphql:/app
    env_file:
      - ./graphql/.env.app
    ports:
      - 8080:8080
    tty: true
  domain-api:
    build:
      context: grpc
      dockerfile: Dockerfile.dev
    volumes:
      - ./grpc:/app
    env_file:
      - ./grpc/.env.app
    ports:
      - 50051:50051
    tty: true
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./postgres/.env.db
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
volumes:
  database:
    driver: local